### ISSUE TITLE
Error since 3.5.6 form 3.5.5

### ISSUE THREAD

**Issue by nWidart** [orchestral/testbench-core#6]
Hello,

I've upgraded testbench-core and testbench to their new patch releases. Since then, my tests are crashing with the following error:

```
PHP Warning:  Uncaught ErrorException: require(/opt/project/vendor/orchestra/testbench-core/laravel/config/filesystems.php): failed to open stream: No such file or directory in /opt/project/vendor/orchestra/testbench-core/src/Bootstrap/LoadConfiguration.php:41
Stack trace:
#0 /opt/project/vendor/orchestra/testbench-core/src/Bootstrap/LoadConfiguration.php(41): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require(/opt/pr...', '/opt/project/ve...', 41, Array)
#1 /opt/project/vendor/orchestra/testbench-core/src/Bootstrap/LoadConfiguration.php(41): require()
#2 /opt/project/vendor/orchestra/testbench-core/src/Bootstrap/LoadConfiguration.php(25): Orchestra\Testbench\Bootstrap\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\Foundation\Application), Object(Illuminate\Config\Repository))
#3 /opt/project/vendor/orchestra/testbench-core/src/Traits/CreatesApplication.php(234): Orchestra\Testbench\Bootstrap\LoadConfiguration->bootstrap(Object(Illuminate\Foundation\Application))
#4 /opt/project/vendor/o in /opt/project/vendor/orchestra/testbench-core/src/Bootstrap/LoadConfiguration.php on line 41
PHP Stack trace:
PHP   1. {main}() /opt/project/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /opt/project/vendor/phpunit/phpunit/phpunit:53
PHP   3. PHPUnit\TextUI\Command->run() /opt/project/vendor/phpunit/phpunit/src/TextUI/Command.php:148
PHP   4. PHPUnit\TextUI\TestRunner->doRun() /opt/project/vendor/phpunit/phpunit/src/TextUI/Command.php:195
PHP   5. PHPUnit\Framework\TestSuite->run() /opt/project/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:546
PHP   6. PHPUnit\Framework\TestSuite->run() /opt/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php:755
PHP   7. PHPUnit\Framework\TestSuite->run() /opt/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php:755
PHP   8. Modules\Media\Tests\EloquentFileRepositoryTest->run() /opt/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php:755
PHP   9. PHPUnit\Framework\TestResult->run() /opt/project/vendor/phpunit/phpunit/src/Framework/TestCase.php:894
PHP  10. Modules\Media\Tests\EloquentFileRepositoryTest->runBare() /opt/project/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
PHP  11. Modules\Media\Tests\EloquentFileRepositoryTest->setUp() /opt/project/vendor/phpunit/phpunit/src/Framework/TestCase.php:935
PHP  12. Modules\Media\Tests\EloquentFileRepositoryTest->setUp() /opt/project/Modules/Media/Tests/EloquentFileRepositoryTest.php:27
PHP  13. Modules\Media\Tests\EloquentFileRepositoryTest->refreshApplication() /opt/project/vendor/orchestra/testbench-core/src/TestCase.php:84
PHP  14. Modules\Media\Tests\EloquentFileRepositoryTest->createApplication() /opt/project/vendor/orchestra/testbench-core/src/TestCase.php:107
PHP  15. Modules\Media\Tests\EloquentFileRepositoryTest->resolveApplicationConfiguration() /opt/project/vendor/orchestra/testbench-core/src/Traits/CreatesApplication.php:203
PHP  16. Orchestra\Testbench\Bootstrap\LoadConfiguration->bootstrap() /opt/project/vendor/orchestra/testbench-core/src/Traits/CreatesApplication.php:234
PHP  17. Orchestra\Testbench\Bootstrap\LoadConfiguration->loadConfigurationFiles() /opt/project/vendor/orchestra/testbench-core/src/Bootstrap/LoadConfiguration.php:25
PHP Fatal error:  Orchestra\Testbench\Bootstrap\LoadConfiguration::loadConfigurationFiles(): Failed opening required '/opt/project/vendor/orchestra/testbench-core/laravel/config/filesystems.php' (include_path='.:/usr/share/php') in /opt/project/vendor/orchestra/testbench-core/src/Bootstrap/LoadConfiguration.php on line 41
```

I'm not sure why the filesystem config file isn't present.

Did I miss something?

Thank you!

**Comment by nWidart** [comment]
Hm ok this is odd. I've re-run the same test suite without changes to the code base. And everything is green again, no crashes.

Maybe some sort of cache/disk update since the update.

Sorry for the trouble!
